title: ERR0R4O2
description: |
  When I sleep
  My dreams soundtrack
  feature EDM
owner: Error4o2 a.k.a AlterodiO
first_published: 2019 # if migrating another site, the year of your first publish
email: alterodio@gmail.com
baseurl: "/error402"
url: "http://chapuisk.github.io/error402.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Error402
  github: https://github.com/chapuisk
  #linkedin-square: https://linkedin.com/in/<username>
  soundcloud: https://soundcloud.com/error4o2

# Build settings
markdown: kramdown
#sass:
#  style: compressed
